import React from "react";
import ReactDOM from "react-dom/client";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

// App shell mounts here. Surfaces (MRI, Panels, Overview, Timeline, Notifications,
// Export) live under src/surfaces/. The API client + hooks are generated by Orval
// into src/api/generated from the backend's OpenAPI schema — never hand-written.
const queryClient = new QueryClient();

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <QueryClientProvider client={queryClient}>
      <div>OSLO — Release 1</div>
    </QueryClientProvider>
  </React.StrictMode>,
);
