import React from "react";
import ReactDOM from "react-dom/client";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { RouterProvider } from "@tanstack/react-router";
import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import { theme } from "./theme";
import { router } from "./app/router";

// App shell mounts here (DTM-0019): the MUI Intralign ThemeProvider + CssBaseline,
// the TanStack QueryClient wired to the DTM-0018 Orval client, and the Router tree.
// Surfaces (MRI, Panels, Overview, Timeline, Notifications, Export) live under
// src/surfaces/ and mount into the shell's route placeholders in DTM-0020+. The API
// client + hooks are generated by Orval into src/api/generated — never hand-written.
const queryClient = new QueryClient();

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <QueryClientProvider client={queryClient}>
        <RouterProvider router={router} />
      </QueryClientProvider>
    </ThemeProvider>
  </React.StrictMode>,
);
