#!/usr/bin/env python3
"""DL records helper (DL-065 — Decision-Recording Discipline).

Subcommands:
  next   - print the next free DL number (scans the legacy decision_log + records/)
  index  - regenerate the records index block in decision_log.md (between markers)
  check  - validate the records/ regime (also run by doc_integrity_check.py)

Records live at 00_owner/decisions/records/DL-XXXX-slug.md (DL-065+).
DL-029..DL-064 remain in the frozen decision_log.md and are NOT validated here.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DECISIONS = ROOT / "00_owner/decisions"
LEGACY_LOG = DECISIONS / "decision_log.md"
RECORDS = DECISIONS / "records"
FROZEN_THROUGH = 64  # decision_log.md is the historical ledger through DL-064

REC_NAME_RE = re.compile(r"^DL-(\d{3,})-[a-z0-9][a-z0-9-]*\.md$")
HEAD_DL_RE = re.compile(r"^#\s*DL-(\d{3,})\b")
REQUIRED_FIELDS = ("Decision", "Status")


def legacy_max():
    if not LEGACY_LOG.exists():
        return 0
    nums = [int(n) for n in re.findall(r"^###\s*DL-(\d{3,})\b",
            LEGACY_LOG.read_text(encoding="utf-8", errors="ignore"), re.M)]
    return max(nums) if nums else 0


def record_files():
    return sorted(RECORDS.glob("DL-*.md")) if RECORDS.exists() else []


def record_nums():
    nums = []
    for rf in record_files():
        m = REC_NAME_RE.match(rf.name)
        if m:
            nums.append(int(m.group(1)))
    return nums


def next_number():
    return max([legacy_max()] + record_nums() + [FROZEN_THROUGH]) + 1


def check_records(root=ROOT):
    """Return a list of error strings for the records/ regime (empty == clean)."""
    errs = []
    recs = sorted((root / "00_owner/decisions/records").glob("DL-*.md")) \
        if (root / "00_owner/decisions/records").exists() else []
    seen = {}
    for rf in recs:
        rel = str(rf.relative_to(root))
        if rf.name.startswith("DL-PENDING"):
            errs.append(f"[record-pending] {rel} still DL-PENDING — assign a number before merge (tools/dl_records.py next)")
            continue
        m = REC_NAME_RE.match(rf.name)
        if not m:
            errs.append(f"[record-name] {rel} must be named DL-XXXX-slug.md (zero-padded, kebab-case)")
            continue
        num = int(m.group(1))
        head = rf.read_text(encoding="utf-8", errors="ignore")
        # header DL number must match the filename
        hm = HEAD_DL_RE.search(head[:400])
        if not hm or int(hm.group(1)) != num:
            errs.append(f"[record-header] {rel} '# DL-{num:03d} — …' header missing or mismatched")
        # required fields present (accept bold field, inline "Field:", or "## Field" heading)
        for fld in REQUIRED_FIELDS:
            if not (f"**{fld}" in head or f"{fld}:" in head
                    or re.search(rf"(?mi)^#{{1,6}}\s*{fld}\b", head)):
                errs.append(f"[record-fields] {rel} missing required field '{fld}'")
        # uniqueness
        if num in seen:
            errs.append(f"[record-dup] DL-{num:03d} in both {seen[num]} and {rel}")
        seen[num] = rel
        # records must be DL-065+ (legacy stays in the frozen log)
        if num <= FROZEN_THROUGH:
            errs.append(f"[record-range] {rel} number DL-{num:03d} is in the frozen legacy range (≤ DL-{FROZEN_THROUGH}); records are DL-{FROZEN_THROUGH+1}+")
    return errs


def title_of(rf):
    for line in rf.read_text(encoding="utf-8", errors="ignore").splitlines():
        m = re.match(r"^#\s*(DL-\d{3,}\s*—\s*.+)$", line.strip())
        if m:
            return m.group(1).strip()
    return rf.stem


START = "<!-- RECORDS-INDEX:START (generated by tools/dl_records.py index — do not hand-edit) -->"
END = "<!-- RECORDS-INDEX:END -->"


def build_index_block():
    lines = [START, "", "## Individual Decision Records (DL-065+)", "",
             "_One file per decision per DL-065. Generated — do not hand-edit._", ""]
    for rf in sorted(record_files(), key=lambda p: p.name):
        if rf.name.startswith("DL-PENDING"):
            continue
        lines.append(f"- {title_of(rf)} → `00_owner/decisions/records/{rf.name}`")
    lines += ["", END]
    return "\n".join(lines)


def regenerate_index():
    text = LEGACY_LOG.read_text(encoding="utf-8", errors="ignore")
    block = build_index_block()
    if START in text and END in text:
        new = re.sub(re.escape(START) + r".*?" + re.escape(END), block, text, flags=re.S)
    else:
        new = text.rstrip() + "\n\n---\n\n" + block + "\n"
    LEGACY_LOG.write_text(new, encoding="utf-8")
    try:
        where = LEGACY_LOG.relative_to(ROOT)
    except ValueError:
        where = LEGACY_LOG
    n = len([r for r in record_files() if not r.name.startswith("DL-PENDING")])
    print(f"index: wrote {n} record(s) into {where}")


CHANGELOG = ROOT / "00_owner/changelog/changelog.md"


def next_chg():
    if not CHANGELOG.exists():
        return 1
    nums = [int(n) for n in re.findall(r"^###\s*CHG-(\d{3,})\b",
            CHANGELOG.read_text(encoding="utf-8", errors="ignore"), re.M)]
    return (max(nums) + 1) if nums else 1


def _slugify(s):
    s = re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")
    return s or "decision"


def land(slug, title, body, decided_by, klass, date=None):
    """Create a numbered record from inputs, regenerate the index, append a CHG.
    Returns (dl_number, chg_number). Used by the dl-land workflow (DL-067)."""
    import datetime
    date = date or datetime.date.today().isoformat()
    slug = _slugify(slug)
    dl = next_number()
    chg = next_chg()
    RECORDS.mkdir(parents=True, exist_ok=True)
    rec = RECORDS / f"DL-{dl:03d}-{slug}.md"
    header = (f"# DL-{dl:03d} — {title}\n\n"
              f"- **Date:** {date} · **Status:** Ratified · **Decided by:** {decided_by}\n"
              f"- **Class:** {klass}\n\n")
    rec.write_text(header + body.strip() + "\n", encoding="utf-8")
    regenerate_index()
    chg_block = (f"### CHG-{chg:03d} — DL-{dl:03d}: {title}\n\n"
                 f"- **Date:** {date} · **Authorizing Decision:** DL-{dl:03d}.\n"
                 f"- **Affected Artifacts:** `00_owner/decisions/records/{rec.name}` (new); "
                 f"`00_owner/decisions/decision_log.md` (records index regenerated).\n"
                 f"- **Change Summary:** {title}. Landed via the dl-land workflow (DL-067).\n"
                 f"- **Supersession Reference:** None.\n")
    ctext = CHANGELOG.read_text(encoding="utf-8", errors="ignore")
    marker = "\n---\n\n## Governance Notes"
    if marker in ctext:
        ctext = ctext.replace(marker, "\n" + chg_block + marker, 1)
    else:
        ctext = ctext.rstrip() + "\n\n" + chg_block
    CHANGELOG.write_text(ctext, encoding="utf-8")
    return dl, chg, slug


def main(argv):
    cmd = argv[1] if len(argv) > 1 else ""
    if cmd == "next":
        print(f"DL-{next_number():03d}")
    elif cmd == "next-chg":
        print(f"CHG-{next_chg():03d}")
    elif cmd == "index":
        regenerate_index()
    elif cmd == "check":
        errs = check_records()
        for e in errs:
            print("ERROR " + e)
        print("PASS" if not errs else f"FAIL ({len(errs)} record error(s))")
        return 1 if errs else 0
    elif cmd == "land":
        import argparse
        p = argparse.ArgumentParser(prog="dl_records.py land")
        p.add_argument("--slug", required=True)
        p.add_argument("--title", required=True)
        p.add_argument("--body-file", required=True)
        p.add_argument("--decided-by", default="Idris (Founder Console)")
        p.add_argument("--class", dest="klass", default="A")
        p.add_argument("--date", default=None)
        a = p.parse_args(argv[2:])
        body = Path(a.body_file).read_text(encoding="utf-8")
        dl, chg, slug = land(a.slug, a.title, body, a.decided_by, a.klass, a.date)
        print(f"landed DL-{dl:03d} (CHG-{chg:03d}) — records/DL-{dl:03d}-{slug}.md")
        import os
        gho = os.environ.get("GITHUB_OUTPUT")
        if gho:
            with open(gho, "a", encoding="utf-8") as f:
                f.write(f"dl={dl:03d}\nchg={chg:03d}\nslug={slug}\nbranch=decision/dl-{dl:03d}-{slug}\n")
    else:
        print(__doc__)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
